// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import Header from "@/components/sb/Header";
import Footer from "@/components/sb/footer/Footer_NonBlok.js";
import { fetchConfig } from "@/lib/storyblok";
import { CartProvider } from "../components/CartContext.jsx";

// Shoplist
import { ShoplistContextProvider } from "../components/sb/shoplist/ShoplistContext.jsx";

export const dynamic = "force-dynamic";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const config = await fetchConfig();

  return (
    <StoryBlokProvider>
      <CartProvider>
        <ShoplistContextProvider>
          <html lang="en">
            <body className={`antialiased`}>
              <Header {...config} />
              {children}
              <Footer {...config} />
            </body>
          </html>
        </ShoplistContextProvider>
      </CartProvider>
    </StoryBlokProvider>
  );
}
